### ISSUE TITLE
Crash when using %q

### ISSUE THREAD

**Issue by Kugelblitz101** [mblong/qtoma2#1]
Entering the command `%q` in the OMA2 command window causes the entire program to crash. This also occurs when a script is used (I was attempting to run the batchCorrect script contained within the hobjExample repository). This version of QtOMA2 was built on Windows 10 64 bit using both MinGW 64 bit and MSYS PE 64 bit, both of which exhibit the crashing issue.

**Comment by Kugelblitz101** [comment]
> Entering the command `%q` in the OMA2 command window causes the entire program to crash. This also occurs when a script is used (I was attempting to run the batchCorrect script contained within the hobjExample repository). This version of QtOMA2 was built on Windows 10 64 bit using both MinGW 64 bit and MSYS PE 64 bit, both of which exhibit the crashing issue.

Running the program in the debugger contained in QtCreator reports a Segmentation Fault

**Comment by mblong** [comment]
problem was due to the different way windows/linux handle strlcpy -- changed fullname in image_support.cpp
